### PR TITLE
Add Maven pom.xml

### PR DESCRIPTION
**Pull request by omwah**
Hi, I added a Maven pom.xml that does not require changing the existing directory layout to match the Maven conventions. So now Maven can be used to package the library up and deploy to a Maven repository if desired.

### CODE REVIEW

**Comment by PatPeter** [comment]
Thank you omwah! I actually converted TimeClock, the successor to SQLibrary's SQLTestSuite that was supposed to be an introduction on how to use SQLibrary, to a Maven project and I've been having the worst of a time with it. I'll merge the pull request when I can push 4.1 and 4.2 after I fix my GitHub issues.

**Comment by omwah** [comment]
Were you going to have the TimeClock stuff run as the test phase of a Maven project? 

Also if your already going down this route, maybe we can move the source into "src/main/java' and the plugin.yml to "src/resources". Then the stuff I put in the <build></build> section can be removed.

I made the current pom.xml so I can more easily include this library as a dependency. 

One more thing, you might want to suggest people try and use JarJar:
http://sonatype.github.com/jarjar-maven-plugin/

To pull your library class files into their jar file. I haven't tried this myself, so I don't have a good example yet for doing it.

**Comment by omwah** [comment]
I added a fix for a bug I found with isTable for SQLite

**Comment by PatPeter** [comment]
That's exactly what I _didn't_ want you to do, the bug was already fixed:

http://dev.bukkit.org/server-mods/sqlibrary/files/4-sqlibrary-4-1/

But I can't push 4.1 to GitHub yet.

**Comment by omwah** [comment]
Ok, I backed out my hotfix and moved it to a branch.

**Comment by omwah** [comment]
I've pulled your 4.2 changes into my repo, so the Maven additions should go in easily now I hope.

**Comment by PatPeter** [comment]
Done! Thanks for your contribution.

**Pull request merged**
