### PR TITLE
Add support for Spout Server

### PR DESCRIPTION
**Pull request by ChristopherLMiller**
Signed-off-by: Moose517 moose51789@gmail.com

### CODE REVIEW

**Comment by PatPeter** [comment]
Could you change your line endings to \r\n?

Also, I don't believe renaming the main class to SQLibrarySpout will work.

**Comment by ChristopherLMiller** [comment]
I'm not sure how to correct line endings honestly.  That commit is what i was told to do to fix it but i have no idea.  And i didn't just rename the main class, its a new class that references spout API instead of bukkits.  Spout uses a properties.yml in place of plugin.yml and it will start it up using the spout class.  This is exactly what i do for my plugins that are both bukkit and spout compatible and they work that way.

**Comment by PatPeter** [comment]
What IDE/editor are you using? It should be in the Edit menu somewhere. And if what you say is true, I can just compile it to be used for both Bukkit and Spout, awesome!

**Comment by PatPeter** [comment]
Worst case scenario, you can use regular expressions.

**Pull request merged**
