### PR TITLE
Added a Factory and a Configuration Class

### PR DESCRIPTION
**Pull request by Belphemur**
Hi,

I added a factory and the configuration class that use it.

The Factory do all the check needed on the configuration to be sure it's valid before trying to create the DatabaseHandler. All the check are done in the Configuration class.

I'm using some enum to define the DatabaseType and the Parameter that will be set in the Configuration.

### CODE REVIEW

**Comment by PatPeter** [comment]
I was between two versions of the library, the changelog of which you can see on the project page. I no longer know if merging your changes will work.

**Comment by PatPeter** [comment]
I was afraid renaming Database.java would interfere with the merge, but it worked! Thanks for your contribution.

**Comment by Belphemur** [comment]
Well since you should have receive a email when I pulled, I thought that sending you a message was useless :)

**Comment by PatPeter** [comment]
Yeah, usually I check my e-mail everyday but for whatever reason hadn't checked it for a week. No worries.

**Pull request merged**
